### ISSUE TITLE
О твоих замечаниях 

### ISSUE THREAD

**Issue by V3RGANz** [V3RGANz/NSUCryptoSummerSchool#3]
> Комментарии и вопросы к твоей интерпретации нашего кода:
> 
> 1. Зачем нужны public setW, setH? По-моему, менять матрицу напрямую таким образом не ок.
> 2. Убери summary, можешь оставить коммент в строке перед идентификатором функции, тогда в Студии будет всплывающая подсказка.
> 3. printf("%d\n", A.getW()); (main.cpp) это зачем? Если это нужное, то напиши
> std::cout << endl << A.getW(); как-то так.
> 4. (*this)[i][j] = minvalue + rand() % maxvalue; (matrix.cpp) Ты, наверное, имел в виду % (maxvalue - minvalue + 1), в общем, как было, только там знак перепутан.
> 5. Почему у тебя все классы в 1 заголовочном файле, и зачем тебе header.h? Напиши их в этом header.h хотя бы.
> 6. В чем смысл использовать вектора вместо массивов для хранения матрицы? Ну кроме того, чтобы не передавать длину через параметр, имхо с массивами проще.
> 7. source matrix shouldn't be less than k*k
> 	if (k > (M.getH() < M.getW() ? M.getH() : M.getW()))
> 		this->SetData({}); (grassmanmatrix.cpp) зачем тебе оба измерения проверять, она же квадратная? Ты так-то еще на 0 не проверяешь.
> 8. if (n != 0) { - напиши if (n), не будь Лукасом
> 9. else {
> 			(*this)[line][column] = Minor(K);
> 			if (line == this->getH()) {
> 				line++;
> 				column = 0;
> 			}
> 			else
> 				column++;
> 		} (там же) зачем кусок с line и column засунул в else?
> 
> В общем, разберись с этим, посмотри, че я написал, я, например, С поменял.

**Comment by V3RGANz** [comment]
1. 
Почему не ок? 
2. Ок, ну я код с шарпа просто взял и там начал все менять просто 
3.  Это к отладке было
4.  Я немного запутался тут наверное, просто не помнил, как % в знаковом случае работает. Да, наверное так, как ты сказал
5. Ну я хотел полином в другой пихнуть
6. А почему с массивом проще? ну просто с векторами удобнее менять размеры матрицы, мне кажется. Там все эти динамические функции уже написаны
7. Ну там криво, да и вообще я там exception хотел поставить, но оставил это напотом. Почему только квадратные? смысл тогда тернарного оператора, который у тебя в коде тоже присутствует. Вообще же функцию для общего случая пишем, мы же не колхозники
8. ну так читается лучше, и вроде изначально так и было лол
9. ой тут еще какая-то хуйня, я там уже обновлял код

**Comment by illbegood** [comment]
1.Ну потому что это нарушает инкапсуляцию. Матрицу не надо менять ручками, а только заданными инструментами. Представь, какой-нибудь клиент будет менять w и h(это правда, не совсем про наш случай), а разработчику придется делать проверки в своих функциях, все ли там в порядке. Просто правила "хорошего тона". Какие-то еще ресайзы там делаешь, не надо так.
4. А ну еще нужно проверить minvalue < maxvalue
5. Типа все что про матрицы в matrix.h? Ну у тебя же залоговочный файл относится не к matrix.cpp, сделал бы, чтоб понятно было, что и откуда.
6.  Зачем изменять размер матрицы? Массивы проще записываются, они легче, насчет быстрее не уверен, правда.
7. Да, тернарный тоже не нужен. Зачем для общего, нужно писать только то, что требуется.
8. В шарпе нельзя просто неявно int к bool привести. Наоборот if (n) нормально.

Поменяй C, добавь, наверное, верхние границы для w и h, как у меня.
На этих плюсах все как-то в несколько раз длиннее получилось.
Вижу, ты их фигню начал переписывать. Тебе помочь или ты сам?

**Comment by illbegood** [comment]
От вектора, наверное, еще нужно избавляться в деструкторе, не знаю.

**Comment by illbegood** [comment]
Если надо, можем в дискорд зайти обсудить.

**Comment by V3RGANz** [comment]
Ок

**Comment by V3RGANz** [comment]
Сейчас
